### PR TITLE
Exercise (16.07.2019)

### PR DESCRIPTION
**Pull request by iwbh15**
Exp and Log function included in CLIJ

### CODE REVIEW

**Comment by haesleinhuepf** [comment]
Hey @iwbh15 ,

this is amazing! Thanks a lot for your work! Just one thing: The code in [CLIJs master branch is frozen](https://clij.github.io/clij-docs/release_cycle) at the moment until its next major release in June 2020. In the meantime, I'm collecting new functionality in the [clij-advanced-filters repository](https://github.com/clij/clij-advanced-filters) - a playground-like place where we can test new stuff before it becomes part of the major distribution. 
https://github.com/clij/clij-advanced-filters

Would you mind sending the pull-request there? I can also put your code in manually.... As you wish.

Thanks a thousand times for your contribution! I'd love to build a community of developers around clij.

Cheers,
Robert

**Comment by iwbh15** [comment]
Hi Robert,
I'm happy to contribute a little to your brilliant and exciting CLIJ
project.
For a long time I was looking for this kind of GPU support in IJ.
I will put the new functions in the advanced-filters project.
Should I close my current and create new pull requests?
Regards,
Peter

**Comment by iwbh15** [comment]
I will close this PR, resort the code a open a new one.

**Comment by haesleinhuepf** [comment]
Hi @iwbh15 ,

thanks for that! I will put your rotate2D bugfix in clij-core anyway. Exponential and logarithm would perfectly fit in clij-advanced-filters. Just put the static methods from the Kernels class and the macro-layer together in one class as for example I've done for [Presign](https://github.com/clij/clij-advanced-filters/blob/master/src/main/java/net/haesleinhuepf/clij/advancedfilters/Presign.java#L286). Mid-term I'm planning to resolve the Kernels class because it would otherwise grow from here to the moon. Thanks again! Looking forward to the next PR!

Cheers,
Robert

**Pull request closed without merging**
